// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: category_message.proto

package product_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Img           string                 `protobuf:"bytes,4,opt,name=img,proto3" json:"img,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     string                 `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_category_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_category_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_category_message_proto_rawDescGZIP(), []int{0}
}

func (x *Category) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Category) GetImg() string {
	if x != nil {
		return x.Img
	}
	return ""
}

func (x *Category) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Category) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Category) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

type CategoryCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryName  string                 `protobuf:"bytes,1,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Img           string                 `protobuf:"bytes,3,opt,name=img,proto3" json:"img,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryCreateReq) Reset() {
	*x = CategoryCreateReq{}
	mi := &file_category_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryCreateReq) ProtoMessage() {}

func (x *CategoryCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_category_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryCreateReq.ProtoReflect.Descriptor instead.
func (*CategoryCreateReq) Descriptor() ([]byte, []int) {
	return file_category_message_proto_rawDescGZIP(), []int{1}
}

func (x *CategoryCreateReq) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *CategoryCreateReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CategoryCreateReq) GetImg() string {
	if x != nil {
		return x.Img
	}
	return ""
}

type CategoryGetListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Category      []*Category            `protobuf:"bytes,2,rep,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryGetListResp) Reset() {
	*x = CategoryGetListResp{}
	mi := &file_category_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryGetListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryGetListResp) ProtoMessage() {}

func (x *CategoryGetListResp) ProtoReflect() protoreflect.Message {
	mi := &file_category_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryGetListResp.ProtoReflect.Descriptor instead.
func (*CategoryGetListResp) Descriptor() ([]byte, []int) {
	return file_category_message_proto_rawDescGZIP(), []int{2}
}

func (x *CategoryGetListResp) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CategoryGetListResp) GetCategory() []*Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type CategoryUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryName  string                 `protobuf:"bytes,1,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryUpdateReq) Reset() {
	*x = CategoryUpdateReq{}
	mi := &file_category_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryUpdateReq) ProtoMessage() {}

func (x *CategoryUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_category_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryUpdateReq.ProtoReflect.Descriptor instead.
func (*CategoryUpdateReq) Descriptor() ([]byte, []int) {
	return file_category_message_proto_rawDescGZIP(), []int{3}
}

func (x *CategoryUpdateReq) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *CategoryUpdateReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CategoryUpdateReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SubCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId    string                 `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Img           string                 `protobuf:"bytes,5,opt,name=img,proto3" json:"img,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     string                 `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubCategory) Reset() {
	*x = SubCategory{}
	mi := &file_category_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubCategory) ProtoMessage() {}

func (x *SubCategory) ProtoReflect() protoreflect.Message {
	mi := &file_category_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubCategory.ProtoReflect.Descriptor instead.
func (*SubCategory) Descriptor() ([]byte, []int) {
	return file_category_message_proto_rawDescGZIP(), []int{4}
}

func (x *SubCategory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubCategory) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *SubCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubCategory) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SubCategory) GetImg() string {
	if x != nil {
		return x.Img
	}
	return ""
}

func (x *SubCategory) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SubCategory) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *SubCategory) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

type SubCategoryCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryName  string                 `protobuf:"bytes,1,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Img           string                 `protobuf:"bytes,3,opt,name=img,proto3" json:"img,omitempty"`
	CategoryId    string                 `protobuf:"bytes,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubCategoryCreateReq) Reset() {
	*x = SubCategoryCreateReq{}
	mi := &file_category_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubCategoryCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubCategoryCreateReq) ProtoMessage() {}

func (x *SubCategoryCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_category_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubCategoryCreateReq.ProtoReflect.Descriptor instead.
func (*SubCategoryCreateReq) Descriptor() ([]byte, []int) {
	return file_category_message_proto_rawDescGZIP(), []int{5}
}

func (x *SubCategoryCreateReq) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *SubCategoryCreateReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SubCategoryCreateReq) GetImg() string {
	if x != nil {
		return x.Img
	}
	return ""
}

func (x *SubCategoryCreateReq) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

type SubCategoryGetListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Subcategory   []*SubCategory         `protobuf:"bytes,2,rep,name=subcategory,proto3" json:"subcategory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubCategoryGetListResp) Reset() {
	*x = SubCategoryGetListResp{}
	mi := &file_category_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubCategoryGetListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubCategoryGetListResp) ProtoMessage() {}

func (x *SubCategoryGetListResp) ProtoReflect() protoreflect.Message {
	mi := &file_category_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubCategoryGetListResp.ProtoReflect.Descriptor instead.
func (*SubCategoryGetListResp) Descriptor() ([]byte, []int) {
	return file_category_message_proto_rawDescGZIP(), []int{6}
}

func (x *SubCategoryGetListResp) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SubCategoryGetListResp) GetSubcategory() []*SubCategory {
	if x != nil {
		return x.Subcategory
	}
	return nil
}

type SubCategoryUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryName  string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CategoryId    string                 `protobuf:"bytes,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubCategoryUpdateReq) Reset() {
	*x = SubCategoryUpdateReq{}
	mi := &file_category_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubCategoryUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubCategoryUpdateReq) ProtoMessage() {}

func (x *SubCategoryUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_category_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubCategoryUpdateReq.ProtoReflect.Descriptor instead.
func (*SubCategoryUpdateReq) Descriptor() ([]byte, []int) {
	return file_category_message_proto_rawDescGZIP(), []int{7}
}

func (x *SubCategoryUpdateReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubCategoryUpdateReq) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *SubCategoryUpdateReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SubCategoryUpdateReq) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

var File_category_message_proto protoreflect.FileDescriptor

const file_category_message_proto_rawDesc = "" +
	"\n" +
	"\x16category_message.proto\x12\x0fproduct_service\"\xbf\x01\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03img\x18\x04 \x01(\tR\x03img\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\a \x01(\tR\tdeletedAt\"l\n" +
	"\x11CategoryCreateReq\x12#\n" +
	"\rcategory_name\x18\x01 \x01(\tR\fcategoryName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x10\n" +
	"\x03img\x18\x03 \x01(\tR\x03img\"b\n" +
	"\x13CategoryGetListResp\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x125\n" +
	"\bcategory\x18\x02 \x03(\v2\x19.product_service.CategoryR\bcategory\"j\n" +
	"\x11CategoryUpdateReq\x12#\n" +
	"\rcategory_name\x18\x01 \x01(\tR\fcategoryName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"\xe3\x01\n" +
	"\vSubCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\tR\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x10\n" +
	"\x03img\x18\x05 \x01(\tR\x03img\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\b \x01(\tR\tdeletedAt\"\x90\x01\n" +
	"\x14SubCategoryCreateReq\x12#\n" +
	"\rcategory_name\x18\x01 \x01(\tR\fcategoryName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x10\n" +
	"\x03img\x18\x03 \x01(\tR\x03img\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\tR\n" +
	"categoryId\"n\n" +
	"\x16SubCategoryGetListResp\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12>\n" +
	"\vsubcategory\x18\x02 \x03(\v2\x1c.product_service.SubCategoryR\vsubcategory\"\x8e\x01\n" +
	"\x14SubCategoryUpdateReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\tR\n" +
	"categoryIdB\x1aZ\x18genproto/product_serviceb\x06proto3"

var (
	file_category_message_proto_rawDescOnce sync.Once
	file_category_message_proto_rawDescData []byte
)

func file_category_message_proto_rawDescGZIP() []byte {
	file_category_message_proto_rawDescOnce.Do(func() {
		file_category_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_category_message_proto_rawDesc), len(file_category_message_proto_rawDesc)))
	})
	return file_category_message_proto_rawDescData
}

var file_category_message_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_category_message_proto_goTypes = []any{
	(*Category)(nil),               // 0: product_service.Category
	(*CategoryCreateReq)(nil),      // 1: product_service.CategoryCreateReq
	(*CategoryGetListResp)(nil),    // 2: product_service.CategoryGetListResp
	(*CategoryUpdateReq)(nil),      // 3: product_service.CategoryUpdateReq
	(*SubCategory)(nil),            // 4: product_service.SubCategory
	(*SubCategoryCreateReq)(nil),   // 5: product_service.SubCategoryCreateReq
	(*SubCategoryGetListResp)(nil), // 6: product_service.SubCategoryGetListResp
	(*SubCategoryUpdateReq)(nil),   // 7: product_service.SubCategoryUpdateReq
}
var file_category_message_proto_depIdxs = []int32{
	0, // 0: product_service.CategoryGetListResp.category:type_name -> product_service.Category
	4, // 1: product_service.SubCategoryGetListResp.subcategory:type_name -> product_service.SubCategory
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_category_message_proto_init() }
func file_category_message_proto_init() {
	if File_category_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_category_message_proto_rawDesc), len(file_category_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_category_message_proto_goTypes,
		DependencyIndexes: file_category_message_proto_depIdxs,
		MessageInfos:      file_category_message_proto_msgTypes,
	}.Build()
	File_category_message_proto = out.File
	file_category_message_proto_goTypes = nil
	file_category_message_proto_depIdxs = nil
}
