// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: product_message.proto

package product_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	IsMain        bool                   `protobuf:"varint,3,opt,name=is_main,json=isMain,proto3" json:"is_main,omitempty"`
	ProductId     string                 `protobuf:"bytes,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductImage) Reset() {
	*x = ProductImage{}
	mi := &file_product_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductImage) ProtoMessage() {}

func (x *ProductImage) ProtoReflect() protoreflect.Message {
	mi := &file_product_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductImage.ProtoReflect.Descriptor instead.
func (*ProductImage) Descriptor() ([]byte, []int) {
	return file_product_message_proto_rawDescGZIP(), []int{0}
}

func (x *ProductImage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductImage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ProductImage) GetIsMain() bool {
	if x != nil {
		return x.IsMain
	}
	return false
}

func (x *ProductImage) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type ProductImagesGetListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductImage  []*ProductImage        `protobuf:"bytes,1,rep,name=productImage,proto3" json:"productImage,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductImagesGetListResp) Reset() {
	*x = ProductImagesGetListResp{}
	mi := &file_product_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductImagesGetListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductImagesGetListResp) ProtoMessage() {}

func (x *ProductImagesGetListResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductImagesGetListResp.ProtoReflect.Descriptor instead.
func (*ProductImagesGetListResp) Descriptor() ([]byte, []int) {
	return file_product_message_proto_rawDescGZIP(), []int{1}
}

func (x *ProductImagesGetListResp) GetProductImage() []*ProductImage {
	if x != nil {
		return x.ProductImage
	}
	return nil
}

func (x *ProductImagesGetListResp) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Img           []*ProductImage        `protobuf:"bytes,5,rep,name=img,proto3" json:"img,omitempty"`
	Quantity      uint64                 `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     string                 `protobuf:"bytes,12,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_product_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_product_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_product_message_proto_rawDescGZIP(), []int{2}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetImg() []*ProductImage {
	if x != nil {
		return x.Img
	}
	return nil
}

func (x *Product) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Product) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Product) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Product) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

type ProductCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Img           []*ProductImage        `protobuf:"bytes,5,rep,name=img,proto3" json:"img,omitempty"`
	Quantity      uint64                 `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductCreateReq) Reset() {
	*x = ProductCreateReq{}
	mi := &file_product_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductCreateReq) ProtoMessage() {}

func (x *ProductCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductCreateReq.ProtoReflect.Descriptor instead.
func (*ProductCreateReq) Descriptor() ([]byte, []int) {
	return file_product_message_proto_rawDescGZIP(), []int{3}
}

func (x *ProductCreateReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductCreateReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProductCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductCreateReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductCreateReq) GetImg() []*ProductImage {
	if x != nil {
		return x.Img
	}
	return nil
}

func (x *ProductCreateReq) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ProductCreateReq) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ProductCreateReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdReq) Reset() {
	*x = GetByIdReq{}
	mi := &file_product_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdReq) ProtoMessage() {}

func (x *GetByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdReq.ProtoReflect.Descriptor instead.
func (*GetByIdReq) Descriptor() ([]byte, []int) {
	return file_product_message_proto_rawDescGZIP(), []int{4}
}

func (x *GetByIdReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReq) Reset() {
	*x = DeleteReq{}
	mi := &file_product_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReq) ProtoMessage() {}

func (x *DeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReq.ProtoReflect.Descriptor instead.
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return file_product_message_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Serch         string                 `protobuf:"bytes,3,opt,name=serch,proto3" json:"serch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListReq) Reset() {
	*x = GetListReq{}
	mi := &file_product_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListReq) ProtoMessage() {}

func (x *GetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListReq.ProtoReflect.Descriptor instead.
func (*GetListReq) Descriptor() ([]byte, []int) {
	return file_product_message_proto_rawDescGZIP(), []int{6}
}

func (x *GetListReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListReq) GetSerch() string {
	if x != nil {
		return x.Serch
	}
	return ""
}

type ProductGetListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductGetListResp) Reset() {
	*x = ProductGetListResp{}
	mi := &file_product_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductGetListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductGetListResp) ProtoMessage() {}

func (x *ProductGetListResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductGetListResp.ProtoReflect.Descriptor instead.
func (*ProductGetListResp) Descriptor() ([]byte, []int) {
	return file_product_message_proto_rawDescGZIP(), []int{7}
}

func (x *ProductGetListResp) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ProductGetListResp) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ProductUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Img           []*ProductImage        `protobuf:"bytes,5,rep,name=img,proto3" json:"img,omitempty"`
	Quantity      uint64                 `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductUpdateReq) Reset() {
	*x = ProductUpdateReq{}
	mi := &file_product_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductUpdateReq) ProtoMessage() {}

func (x *ProductUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductUpdateReq.ProtoReflect.Descriptor instead.
func (*ProductUpdateReq) Descriptor() ([]byte, []int) {
	return file_product_message_proto_rawDescGZIP(), []int{8}
}

func (x *ProductUpdateReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductUpdateReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProductUpdateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductUpdateReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductUpdateReq) GetImg() []*ProductImage {
	if x != nil {
		return x.Img
	}
	return nil
}

func (x *ProductUpdateReq) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ProductUpdateReq) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ProductUpdateReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductUpdateReq) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_product_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_product_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_product_message_proto_rawDescGZIP(), []int{9}
}

var File_product_message_proto protoreflect.FileDescriptor

const file_product_message_proto_rawDesc = "" +
	"\n" +
	"\x15product_message.proto\x12\x0fproduct_service\"h\n" +
	"\fProductImage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x17\n" +
	"\ais_main\x18\x03 \x01(\bR\x06isMain\x12\x1d\n" +
	"\n" +
	"product_id\x18\x04 \x01(\tR\tproductId\"s\n" +
	"\x18ProductImagesGetListResp\x12A\n" +
	"\fproductImage\x18\x01 \x03(\v2\x1d.product_service.ProductImageR\fproductImage\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\xc5\x02\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12/\n" +
	"\x03img\x18\x05 \x03(\v2\x1d.product_service.ProductImageR\x03img\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x04R\bquantity\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\f \x01(\tR\tdeletedAt\"\xf1\x01\n" +
	"\x10ProductCreateReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12/\n" +
	"\x03img\x18\x05 \x03(\v2\x1d.product_service.ProductImageR\x03img\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x04R\bquantity\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\"\x1c\n" +
	"\n" +
	"GetByIdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1b\n" +
	"\tDeleteReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"L\n" +
	"\n" +
	"GetListReq\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x14\n" +
	"\x05serch\x18\x03 \x01(\tR\x05serch\"`\n" +
	"\x12ProductGetListResp\x124\n" +
	"\bproducts\x18\x01 \x03(\v2\x18.product_service.ProductR\bproducts\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"\x90\x02\n" +
	"\x10ProductUpdateReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12/\n" +
	"\x03img\x18\x05 \x03(\v2\x1d.product_service.ProductImageR\x03img\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x04R\bquantity\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"\a\n" +
	"\x05EmptyB\x1aZ\x18genproto/product_serviceb\x06proto3"

var (
	file_product_message_proto_rawDescOnce sync.Once
	file_product_message_proto_rawDescData []byte
)

func file_product_message_proto_rawDescGZIP() []byte {
	file_product_message_proto_rawDescOnce.Do(func() {
		file_product_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_message_proto_rawDesc), len(file_product_message_proto_rawDesc)))
	})
	return file_product_message_proto_rawDescData
}

var file_product_message_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_product_message_proto_goTypes = []any{
	(*ProductImage)(nil),             // 0: product_service.ProductImage
	(*ProductImagesGetListResp)(nil), // 1: product_service.ProductImagesGetListResp
	(*Product)(nil),                  // 2: product_service.Product
	(*ProductCreateReq)(nil),         // 3: product_service.ProductCreateReq
	(*GetByIdReq)(nil),               // 4: product_service.GetByIdReq
	(*DeleteReq)(nil),                // 5: product_service.DeleteReq
	(*GetListReq)(nil),               // 6: product_service.GetListReq
	(*ProductGetListResp)(nil),       // 7: product_service.ProductGetListResp
	(*ProductUpdateReq)(nil),         // 8: product_service.ProductUpdateReq
	(*Empty)(nil),                    // 9: product_service.Empty
}
var file_product_message_proto_depIdxs = []int32{
	0, // 0: product_service.ProductImagesGetListResp.productImage:type_name -> product_service.ProductImage
	0, // 1: product_service.Product.img:type_name -> product_service.ProductImage
	0, // 2: product_service.ProductCreateReq.img:type_name -> product_service.ProductImage
	2, // 3: product_service.ProductGetListResp.products:type_name -> product_service.Product
	0, // 4: product_service.ProductUpdateReq.img:type_name -> product_service.ProductImage
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_product_message_proto_init() }
func file_product_message_proto_init() {
	if File_product_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_message_proto_rawDesc), len(file_product_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_product_message_proto_goTypes,
		DependencyIndexes: file_product_message_proto_depIdxs,
		MessageInfos:      file_product_message_proto_msgTypes,
	}.Build()
	File_product_message_proto = out.File
	file_product_message_proto_goTypes = nil
	file_product_message_proto_depIdxs = nil
}
