// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: services.proto

package product_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PING struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PING) Reset() {
	*x = PING{}
	mi := &file_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PING) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PING) ProtoMessage() {}

func (x *PING) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PING.ProtoReflect.Descriptor instead.
func (*PING) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{0}
}

func (x *PING) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type PONG struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PONG) Reset() {
	*x = PONG{}
	mi := &file_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PONG) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PONG) ProtoMessage() {}

func (x *PONG) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PONG.ProtoReflect.Descriptor instead.
func (*PONG) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{1}
}

func (x *PONG) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_services_proto protoreflect.FileDescriptor

const file_services_proto_rawDesc = "" +
	"\n" +
	"\x0eservices.proto\x12\x0fproduct_service\x1a\x15product_message.proto\x1a\x16category_message.proto\"\x18\n" +
	"\x04PING\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"\x18\n" +
	"\x04PONG\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2B\n" +
	"\x04Ping\x12:\n" +
	"\bSendPing\x12\x15.product_service.PING\x1a\x15.product_service.PONG\"\x002\xc2\f\n" +
	"\x0fProduct_service\x12L\n" +
	"\rCreateProduct\x12!.product_service.ProductCreateReq\x1a\x18.product_service.Product\x12C\n" +
	"\n" +
	"GetProduct\x12\x1b.product_service.GetByIdReq\x1a\x18.product_service.Product\x12O\n" +
	"\vGetProducts\x12\x1b.product_service.GetListReq\x1a#.product_service.ProductGetListResp\x12L\n" +
	"\rUpdateProduct\x12!.product_service.ProductUpdateReq\x1a\x18.product_service.Product\x12C\n" +
	"\rDeleteProduct\x12\x1a.product_service.DeleteReq\x1a\x16.product_service.Empty\x12P\n" +
	"\x10CreateProductImg\x12\x1d.product_service.ProductImage\x1a\x1d.product_service.ProductImage\x12K\n" +
	"\rGetProductImg\x12\x1b.product_service.GetByIdReq\x1a\x1d.product_service.ProductImage\x12X\n" +
	"\x0eGetProductImgs\x12\x1b.product_service.GetListReq\x1a).product_service.ProductImagesGetListResp\x12P\n" +
	"\x10UpdateProductImg\x12\x1d.product_service.ProductImage\x1a\x1d.product_service.ProductImage\x12F\n" +
	"\x10DeleteProductImg\x12\x1a.product_service.DeleteReq\x1a\x16.product_service.Empty\x12O\n" +
	"\x0eCreateCategory\x12\".product_service.CategoryCreateReq\x1a\x19.product_service.Category\x12E\n" +
	"\vGetCategory\x12\x1b.product_service.GetByIdReq\x1a\x19.product_service.Category\x12R\n" +
	"\rGetCategories\x12\x1b.product_service.GetListReq\x1a$.product_service.CategoryGetListResp\x12O\n" +
	"\x0eUpdateCategory\x12\".product_service.CategoryUpdateReq\x1a\x19.product_service.Category\x12D\n" +
	"\x0eDeleteCategory\x12\x1a.product_service.DeleteReq\x1a\x16.product_service.Empty\x12X\n" +
	"\x11SubCreateCategory\x12%.product_service.SubCategoryCreateReq\x1a\x1c.product_service.SubCategory\x12K\n" +
	"\x0eGetSubCategory\x12\x1b.product_service.GetByIdReq\x1a\x1c.product_service.SubCategory\x12X\n" +
	"\x10GetSubCategories\x12\x1b.product_service.GetListReq\x1a'.product_service.SubCategoryGetListResp\x12X\n" +
	"\x11UpdateSubCategory\x12%.product_service.SubCategoryUpdateReq\x1a\x1c.product_service.SubCategory\x12G\n" +
	"\x11DeleteSubCategory\x12\x1a.product_service.DeleteReq\x1a\x16.product_service.EmptyB\x1aZ\x18genproto/product_serviceb\x06proto3"

var (
	file_services_proto_rawDescOnce sync.Once
	file_services_proto_rawDescData []byte
)

func file_services_proto_rawDescGZIP() []byte {
	file_services_proto_rawDescOnce.Do(func() {
		file_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_proto_rawDesc), len(file_services_proto_rawDesc)))
	})
	return file_services_proto_rawDescData
}

var file_services_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_proto_goTypes = []any{
	(*PING)(nil),                     // 0: product_service.PING
	(*PONG)(nil),                     // 1: product_service.PONG
	(*ProductCreateReq)(nil),         // 2: product_service.ProductCreateReq
	(*GetByIdReq)(nil),               // 3: product_service.GetByIdReq
	(*GetListReq)(nil),               // 4: product_service.GetListReq
	(*ProductUpdateReq)(nil),         // 5: product_service.ProductUpdateReq
	(*DeleteReq)(nil),                // 6: product_service.DeleteReq
	(*ProductImage)(nil),             // 7: product_service.ProductImage
	(*CategoryCreateReq)(nil),        // 8: product_service.CategoryCreateReq
	(*CategoryUpdateReq)(nil),        // 9: product_service.CategoryUpdateReq
	(*SubCategoryCreateReq)(nil),     // 10: product_service.SubCategoryCreateReq
	(*SubCategoryUpdateReq)(nil),     // 11: product_service.SubCategoryUpdateReq
	(*Product)(nil),                  // 12: product_service.Product
	(*ProductGetListResp)(nil),       // 13: product_service.ProductGetListResp
	(*Empty)(nil),                    // 14: product_service.Empty
	(*ProductImagesGetListResp)(nil), // 15: product_service.ProductImagesGetListResp
	(*Category)(nil),                 // 16: product_service.Category
	(*CategoryGetListResp)(nil),      // 17: product_service.CategoryGetListResp
	(*SubCategory)(nil),              // 18: product_service.SubCategory
	(*SubCategoryGetListResp)(nil),   // 19: product_service.SubCategoryGetListResp
}
var file_services_proto_depIdxs = []int32{
	0,  // 0: product_service.Ping.SendPing:input_type -> product_service.PING
	2,  // 1: product_service.Product_service.CreateProduct:input_type -> product_service.ProductCreateReq
	3,  // 2: product_service.Product_service.GetProduct:input_type -> product_service.GetByIdReq
	4,  // 3: product_service.Product_service.GetProducts:input_type -> product_service.GetListReq
	5,  // 4: product_service.Product_service.UpdateProduct:input_type -> product_service.ProductUpdateReq
	6,  // 5: product_service.Product_service.DeleteProduct:input_type -> product_service.DeleteReq
	7,  // 6: product_service.Product_service.CreateProductImg:input_type -> product_service.ProductImage
	3,  // 7: product_service.Product_service.GetProductImg:input_type -> product_service.GetByIdReq
	4,  // 8: product_service.Product_service.GetProductImgs:input_type -> product_service.GetListReq
	7,  // 9: product_service.Product_service.UpdateProductImg:input_type -> product_service.ProductImage
	6,  // 10: product_service.Product_service.DeleteProductImg:input_type -> product_service.DeleteReq
	8,  // 11: product_service.Product_service.CreateCategory:input_type -> product_service.CategoryCreateReq
	3,  // 12: product_service.Product_service.GetCategory:input_type -> product_service.GetByIdReq
	4,  // 13: product_service.Product_service.GetCategories:input_type -> product_service.GetListReq
	9,  // 14: product_service.Product_service.UpdateCategory:input_type -> product_service.CategoryUpdateReq
	6,  // 15: product_service.Product_service.DeleteCategory:input_type -> product_service.DeleteReq
	10, // 16: product_service.Product_service.SubCreateCategory:input_type -> product_service.SubCategoryCreateReq
	3,  // 17: product_service.Product_service.GetSubCategory:input_type -> product_service.GetByIdReq
	4,  // 18: product_service.Product_service.GetSubCategories:input_type -> product_service.GetListReq
	11, // 19: product_service.Product_service.UpdateSubCategory:input_type -> product_service.SubCategoryUpdateReq
	6,  // 20: product_service.Product_service.DeleteSubCategory:input_type -> product_service.DeleteReq
	1,  // 21: product_service.Ping.SendPing:output_type -> product_service.PONG
	12, // 22: product_service.Product_service.CreateProduct:output_type -> product_service.Product
	12, // 23: product_service.Product_service.GetProduct:output_type -> product_service.Product
	13, // 24: product_service.Product_service.GetProducts:output_type -> product_service.ProductGetListResp
	12, // 25: product_service.Product_service.UpdateProduct:output_type -> product_service.Product
	14, // 26: product_service.Product_service.DeleteProduct:output_type -> product_service.Empty
	7,  // 27: product_service.Product_service.CreateProductImg:output_type -> product_service.ProductImage
	7,  // 28: product_service.Product_service.GetProductImg:output_type -> product_service.ProductImage
	15, // 29: product_service.Product_service.GetProductImgs:output_type -> product_service.ProductImagesGetListResp
	7,  // 30: product_service.Product_service.UpdateProductImg:output_type -> product_service.ProductImage
	14, // 31: product_service.Product_service.DeleteProductImg:output_type -> product_service.Empty
	16, // 32: product_service.Product_service.CreateCategory:output_type -> product_service.Category
	16, // 33: product_service.Product_service.GetCategory:output_type -> product_service.Category
	17, // 34: product_service.Product_service.GetCategories:output_type -> product_service.CategoryGetListResp
	16, // 35: product_service.Product_service.UpdateCategory:output_type -> product_service.Category
	14, // 36: product_service.Product_service.DeleteCategory:output_type -> product_service.Empty
	18, // 37: product_service.Product_service.SubCreateCategory:output_type -> product_service.SubCategory
	18, // 38: product_service.Product_service.GetSubCategory:output_type -> product_service.SubCategory
	19, // 39: product_service.Product_service.GetSubCategories:output_type -> product_service.SubCategoryGetListResp
	18, // 40: product_service.Product_service.UpdateSubCategory:output_type -> product_service.SubCategory
	14, // 41: product_service.Product_service.DeleteSubCategory:output_type -> product_service.Empty
	21, // [21:42] is the sub-list for method output_type
	0,  // [0:21] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_services_proto_init() }
func file_services_proto_init() {
	if File_services_proto != nil {
		return
	}
	file_product_message_proto_init()
	file_category_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_proto_rawDesc), len(file_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_services_proto_goTypes,
		DependencyIndexes: file_services_proto_depIdxs,
		MessageInfos:      file_services_proto_msgTypes,
	}.Build()
	File_services_proto = out.File
	file_services_proto_goTypes = nil
	file_services_proto_depIdxs = nil
}
